### PR TITLE
Add WMTS tile layer

### PR DESCRIPTION
**Pull request by paul121**
Tested with this behavior:
```js
      var opts = {
          title: 'Norkart Flyfoto',
          url: 'http://opencache.statkart.no/gatekeeper/gk/gk.open_wmts',
          group: 'Base layers',
          params: {
            layer: 'topo4',
            format: 'image/png',
          }
        };
      myMap.addLayer('wmts', opts)
```

Screenshot_2020-04-10 farmOS Map

Before: 519.3Kb
After: 523.3Kb

The OL [`ol/source/WMTS` API](https://openlayers.org/en/latest/apidoc/module-ol_source_WMTS-WMTS.html) seems to be a bit different than others that are already implemented here.. most notably, there isn't a `params` attribute in the `options` that are passed to the WMTS source, and a `layer` attribute seems to be required (at least for the Norwegian tile server). Rather than adding `layer` as an attribute under `opts`, I'm keeping it under `opts.params` - is that OK?

I also tried implementing the [WMTS Capabilites](https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html) functionality but had some trouble adding this in. The Norwegian server provides a capability doc: (neat to see what all layers are available!): http://opencache.statkart.no/gatekeeper/gk/gk.open_wmts?Version=1.0.0&service=wmts&request=getcapabilities

### CODE REVIEW

**Comment by mstenta** [comment]
Thanks @paul121! Overall this looks good!

There are some linting issues - can you fix the syntax for consistency?

I just pushed two commits to master that should make that easier for you. You can just run `npm run lint` from the root directory and it will print out a summary of all the issues. Here is what I get:

```js
$ npm run lint

> farmOS-map@1.1.0 lint /usr/src/app
> eslint --color src


/usr/src/app/src/instance/methods/layer.js
   16:8   error  A space is required after '{'                                                           object-curly-spacing
   16:29  error  A space is required before '}'                                                          object-curly-spacing
   17:8   error  A space is required after '{'                                                           object-curly-spacing
   17:29  error  A space is required before '}'                                                          object-curly-spacing
  168:3   error  Unexpected var, use let or const instead                                                no-var
  169:3   error  Unexpected var, use let or const instead                                                no-var
  172:3   error  Unexpected var, use let or const instead                                                no-var
  173:3   error  Split 'var' declarations into multiple statements                                       one-var
  173:3   error  Unexpected var, use let or const instead                                                no-var
  176:8   error  All 'var' declarations must be at the top of the function scope                         vars-on-top
  176:8   error  Unexpected var, use let or const instead                                                no-var
  176:27  error  Unary operator '++' used                                                                no-plusplus
  176:34  error  Expected exception block, space or tab after '//' in comment                            spaced-comment
  178:29  error  'Math.pow' is restricted from being used. Use the exponentiation operator (**) instead  no-restricted-properties
  179:20  error  Unexpected string concatenation                                                         prefer-template
  179:34  error  Strings must use singlequote                                                            quotes
  185:25  error  Trailing spaces not allowed                                                             no-trailing-spaces
  191:16  error  Missing trailing comma                                                                  comma-dangle
  193:5   error  Missing semicolon                                                                       semi

```

So you might want to just rebase this on top of master and run `npm run lint` to see that yourself. If you use Atom, you can also install the Linter and Linter-ESLint packages and it will show it to you in the IDE.

Aside from that, I'm also curious to understand the WMTS requirements a bit more, and what the extra code is doing.

Specifically:

```
  // Save the projection and projectionExtent.
  var sProjection = projection.featureProjection;
  var projectionExtent = getProjection(sProjection).getExtent();

  // Calculate values for WMTSTileGrid.
  var size = getWidth(projectionExtent) / 256;
  var resolutions = [],
    matrixIds = [];

  for (var z = 0; z < 15; ++z) { //Max 18?
    // generate resolutions and matrixIds arrays for this WMTS
    resolutions[z] = size / Math.pow(2, z);
    matrixIds[z] = sProjection + ":" + z;
  }
```

I assume this was largely copied from the old source that was removed from the `farm_map_no` module? https://github.com/farmOS/farm_map_no/commit/461e7b0deb01c8933ce3124af10c2dbc75ee10da#diff-21ce3c436dab0942e7fe2bb30539436e

To be honest, I never quite understood what all that was doing. I worked with @svenn in farmOS IRC to get it working, and I forget where that code came from. It might be specific to that particular WMTS source, though. So I want to make sure whatever we include in farmOS-map is general enough to support other sources as well. I'd like to improve the comments above each of those chunks of code to better understand what it's doing (and why) at a glance.

The risk is we merge an `addWMTSLayer()` and then have to change its public API surface in the future.

I honestly don't know enough about WMTS sources, and would like to wrap my head around their requirements a bit more. Documenting some of this in #63 might also be worthwhile, if there is a lot to it (and maybe the README.md as well, if we find we need to support more optional parameters in the `addWMTSLayer()` function.

Thanks again for getting this started!

**Comment by mstenta** [comment]
Oh just saw that I linked to the original source of that code: https://github.com/kartverket/example-clients/blob/master/openlayers3/wmts_mercator.html

**Comment by paul121** [comment]
> There are some linting issues - can you fix the syntax for consistency?

Ah of course. Thanks for adding that helper. I'll add that to my IDE too!

> Aside from that, I'm also curious to understand the WMTS requirements a bit more, and what the extra code is doing. .... I assume this was largely copied from the old source that was removed from the farm_map_no module?

That's correct, it is the same code that is used in the example online. I believe this example code assumes tile sizes of 256x256, and assumes an origin at the projection's upper left - likely common defaults, but something that should be configurable. These values are all used to build the `TileGrid` - here are docs on the [WMTSTileGrid](https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS-WMTSTileGrid.html) which has some good info.

It was for these reasons I started going down the [WMTS Capabilities](https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html)) route... as you can tell from that example this doesn't require as many config options - because the server defines them itself. It does add the complexity of requiring a `fetch` to retrieve the capabilities doc before building the layer source (I had some trouble adding this into `layers.js` but didn't spend much time on it)

> The risk is we merge an addWMTSLayer() and then have to change its public API surface in the future.

After looking at this further... perhaps we should only add support for the WMTS capabilites doc.  It seems like we would need to mirror almost all of the WMTS TileGrid API to allow for "full" customization of WMTS sources. The alternative would be supporting the WMTS capabilities doc... which is designed to do this in the first place. It also allows for servers to change config, without breaking hard-coded config in OL.

**Comment by mstenta** [comment]
Oops - I changed the default branch to `1.x` - forgot that this would affect open PRs. :-(

**Comment by mstenta** [comment]
Sorry @paul121! You can open a new PR against `1.x` if you'd like...

**Pull request closed without merging**
