### PR TITLE
Google

### PR DESCRIPTION
**Pull request by mstenta**
See https://github.com/farmOS/farmOS-map/issues/8

### CODE REVIEW

**Comment by mstenta** [comment]
If https://github.com/mapgears/ol3-google-maps/pull/259 is merged, we can remove `combine: true` from all the Google layers.

**Comment by mstenta** [comment]
I'm also thinking about removing the "Base layers" group entirely, so OSM is on the same root level as the Google layers. Google layers do not currently work in a sub-group.

See this comment for the summary of compatibility issues between `ol3-google-maps` and `ol-layerswitcher`: https://github.com/mapgears/ol3-google-maps/issues/37#issuecomment-523199094

**Comment by mstenta** [comment]
> If mapgears/ol3-google-maps#259 is merged, we can remove combine: true from all the Google layers.

I pushed a `google2` branch that contains this change, for if/when that PR is merged.

**Comment by jgaehring** [comment]
I'm not sure if you want to keep waiting on my review. I wasn't able to get it to work in the client, and I'm still not sure what the cause is (possibly a bug in one of the dependencies). I'm shelving Google Maps integration for now to work on drawing in the client map.

**Comment by mstenta** [comment]
FYI https://github.com/mapgears/ol3-google-maps/pull/259 has been merged, but not included in a new release yet.

**Pull request merged**
