### PR TITLE
Fixed release workflow to include all built JS/CSS/etc with the "farmOS-map" prefix

### PR DESCRIPTION
**Pull request by symbioquine**
The issue here is that farmOS-map now builds a bunch of JS/CSS chunk files which are necessary for all of farmOS-map's behaviors to work correctly;

```sh
$ ls dist/
farmOS-map-chunk-0111d8061b9a50abef47.css             farmOS-map-chunk-39735a460ef847f90727.js              farmOS-map-chunk-647bd575b50bb76e6f50.js.LICENSE.txt  farmOS-map-chunk-faad37df3b638bef23f7.css
farmOS-map-chunk-089772494e93c03bb076.js              farmOS-map-chunk-39735a460ef847f90727.js.LICENSE.txt  farmOS-map-chunk-72ba8dece6e00934eef6.js              farmOS-map.css
farmOS-map-chunk-089772494e93c03bb076.js.LICENSE.txt  farmOS-map-chunk-3f9ff02a0a072d830cb1.css             farmOS-map-chunk-72ba8dece6e00934eef6.js.LICENSE.txt  farmOS-map.js
farmOS-map-chunk-1035a45deaad9c087345.js              farmOS-map-chunk-5547e19bfe3adbd33a82.css             farmOS-map-chunk-a0608a8045d2ff14b759.js              farmOS-map.js.LICENSE.txt
farmOS-map-chunk-1035a45deaad9c087345.js.LICENSE.txt  farmOS-map-chunk-563e7276f62b25852291.js              farmOS-map-chunk-a0608a8045d2ff14b759.js.LICENSE.txt  index.html
farmOS-map-chunk-13e8e7684df1e30b8f47.js              farmOS-map-chunk-563e7276f62b25852291.js.LICENSE.txt  farmOS-map-chunk-d4168f1434aea493c1b1.css             mapbox.js
farmOS-map-chunk-13e8e7684df1e30b8f47.js.LICENSE.txt  farmOS-map-chunk-5af39167a4e1d678c260.js              farmOS-map-chunk-e19c1353e1d0b55e0be2.js
farmOS-map-chunk-22be7f44929bde3f5135.js              farmOS-map-chunk-5af39167a4e1d678c260.js.LICENSE.txt  farmOS-map-chunk-e19c1353e1d0b55e0be2.js.LICENSE.txt
farmOS-map-chunk-22be7f44929bde3f5135.js.LICENSE.txt  farmOS-map-chunk-647bd575b50bb76e6f50.js              farmOS-map-chunk-f6ac84ea1eeacb673ccc.css
```

### CODE REVIEW

**Comment by paul121** [comment]
@symbioquine oh yeah, I should have mentioned that in my PR #128.

I noticed these but thought those were only necessary when farmOS-map was being bundled with webpack, not for this release artifact. But are they needed for the "external linking" use case too?

**Comment by mstenta** [comment]
LGTM

**Comment by paul121** [comment]
But yes LGTM if this is indeed needed!

**Comment by symbioquine** [comment]
This was pushed as part of v2.0.1 release: https://github.com/farmOS/farmOS-map/commit/c485cdb700b4f282260d2fba9f93caf66fcdd9fd

**Pull request closed without merging**
