### PR TITLE
Add GeoJSON layer from object, instead of URL #76

### PR DESCRIPTION
**Pull request by mstenta**
See https://github.com/farmOS/farmOS-map/issues/76

### CODE REVIEW

**Comment by mstenta** [comment]
This is not tested yet. Test before merging!

**Comment by jgaehring** [comment]
This is working in Field Kit with OAuth. Just had to add the projection for the GeoJSON format to work properly. I also tweaked the language in the docs and an error message where it referred to the `geojson` prop as a "string" instead of an "object".

**Comment by mstenta** [comment]
Thanks @jgaehring ! I'll try to test this myself soon... I'm curious about the GeoJSON projection, and why that wasn't needed for loading via URL but is needed now. I can dig into it and see if I find anything...

**Comment by jgaehring** [comment]
Here's a snippet you can run in your console to test it out:

```js
let geojson = {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-73.90057799599745,40.7126140355544],[-73.89120229896434,40.70870524041186],[-73.89027269088608,40.70826810927258],[-73.89107992892384,40.70516896399636],[-73.89430888107492,40.70092467756794],[-73.89915230930161,40.6958114338448],[-73.92167685454919,40.70937350199137],[-73.91889058132207,40.71219611800268],[-73.91568766910767,40.71341987237579],[-73.90057799599745,40.7126140355544]]]},"properties":{"name":"\u003Ca href=\u0022\/farm\/area\/ridgewood\u0022\u003ERidgewood\u003C\/a\u003E","description":"\u003Cdiv class=\u0022area-details\u0022 id=\u0022area-details-10\u0022\u003E\u003C\/div\u003E"}}]};
myMap.addLayer('geojson', { geojson });
myMap.zoomToVectors();
```

**Pull request merged**
